apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhdh-book1-templates
  annotations:
    github.com/project-slug: clecioantao/rhdh-book1-templates
spec:
  type: other
  lifecycle: unknown
  owner: clecioantao
