apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nestjs-with-postgres
  title: NestJS Service with backing PostgreSQL database
  description: Creates a NestJS Service together with a PostgreSQL database
  tags:
    - nodejs
    - nestjs
    - database
    - postgresql
    - book
spec:
  owner: user:clecioantao
  type: service

  parameters:
    - title: Provide information about the GitHub location
      required:
        - githubOrg
      properties:
        githubOrg:
          title: Repo Owner (GitHub user/org)
          type: string
          default: clecioantao
        description:
          title: Description
          type: string
          default: Creates a NestJS Service together with a PostgreSQL database
    - title: Provide information about the new component
      required:
        - namespace
        - application_id
        - owner
      properties:
        namespace:
          title: Namespace
          type: string
        application_id: 
          title: Application Id
          type: string
        owner:
          title: Owner
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: [User]
    - title: Provide Build Information
      required:
        - image_host
        - image_tag
      properties:
        image_host:
          title: Image Host
          type: string
          default: ghcr.io
        image_tag:
          title: Image Tag
          default: latest
          type: string

  steps:
    - id: templateSource
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./source
        values:
          githubOrg: ${{parameters.githubOrg}}
          repoName: ${{parameters.namespace}}-${{parameters.application_id}}
          owner: ${{parameters.owner}}
          namespace: ${{parameters.namespace}}
          component_id: ${{parameters.namespace}}-${{parameters.application_id}}
          description: ${{parameters.description}}

    - id: publishSource
      name: Publishing to GitHub
      action: publish:github
      input:
        sourcePath: ./source
        repoUrl: github.com?owner=${{parameters.githubOrg}}&repo=${{parameters.namespace}}-${{parameters.application_id}}
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public
        description: ${{parameters.description}}

    - id: registerSource
      name: Register in Backstage Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{steps.publishSource.output.repoContentsUrl}}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Source Code Repository
        url: ${{steps.publishSource.output.remoteUrl}}
      - title: Open NestJS Component
        icon: catalog
        entityRef: ${{steps.registerSource.output.entityRef}}
